import type { Player, Tournament } from '../../shared/types/domain'

const players: Record<'a' | 'b' | 'c' | 'd', Player[]> = {
  a: [
    { id: 'p-a1', name: 'Luca Bianchi', nickname: 'Laser', gender: 'man', accessToken: 'tok_laser_7fA91' },
    { id: 'p-a2', name: 'Marta Riva', nickname: 'Volpe', gender: 'woman', accessToken: 'tok_volpe_3dK22' },
    { id: 'p-a3', name: 'Nico Serra', nickname: 'Turbo', gender: 'man', accessToken: 'tok_turbo_8hP19' },
  ],
  b: [
    { id: 'p-b1', name: 'Sara Conti', nickname: 'Slam', gender: 'woman', accessToken: 'tok_slam_2nQ51' },
    { id: 'p-b2', name: 'Diego Ferri', nickname: 'D-Fire', gender: 'man', accessToken: 'tok_dfire_5zM66' },
    { id: 'p-b3', name: 'Elia Costa', nickname: 'Muro', gender: 'man', accessToken: 'tok_muro_9aX44' },
  ],
  c: [
    { id: 'p-c1', name: 'Giada Mori', nickname: 'Ace', gender: 'woman', accessToken: 'tok_ace_1qW72' },
    { id: 'p-c2', name: 'Paolo Neri', nickname: 'Spin', gender: 'man', accessToken: 'tok_spin_6rT80' },
    { id: 'p-c3', name: 'Irene Villa', nickname: 'Ivy', gender: 'woman', accessToken: 'tok_ivy_4bC03' },
  ],
  d: [
    { id: 'p-d1', name: 'Tommaso Greco', nickname: 'T-Grex', gender: 'man', accessToken: 'tok_tgrex_0vL11' },
    { id: 'p-d2', name: 'Alma Fonti', nickname: 'Flash', gender: 'woman', accessToken: 'tok_flash_7yN38' },
    { id: 'p-d3', name: 'Ruben Sala', nickname: 'Chop', gender: 'man', accessToken: 'tok_chop_2sH84' },
  ],
}

export const tournament: Tournament = {
  id: 'tour-kaos-2026',
  name: 'Padel Kaos Opening Night',
  groups: [
    { id: 'g-alpha', name: 'Girone Alpha' },
    { id: 'g-beta', name: 'Girone Beta' },
  ],
  courts: [
    { id: 'court-1', name: 'Campo 1' },
    { id: 'court-2', name: 'Campo 2' },
    { id: 'court-3', name: 'Campo 3' },
  ],
  teams: [
    { id: 'team-a', name: 'Milano Thunder', shortName: 'MTH', color: '#FFD000', groupId: 'g-alpha', players: players.a },
    { id: 'team-b', name: 'Roma Smash', shortName: 'RSM', color: '#00D1FF', groupId: 'g-alpha', players: players.b },
    { id: 'team-c', name: 'Torino Rebels', shortName: 'TRB', color: '#FF4D6D', groupId: 'g-beta', players: players.c },
    { id: 'team-d', name: 'Napoli Volt', shortName: 'NPV', color: '#38E078', groupId: 'g-beta', players: players.d },
  ],
  matches: [
    {
      id: 'match-1',
      courtId: 'court-1',
      groupId: 'g-alpha',
      teamAId: 'team-a',
      teamBId: 'team-b',
      status: 'kaos_event',
      score: { currentSet: 2, points: { A: '40', B: '30' }, games: { A: 2, B: 1 }, sets: { A: 1, B: 0 } },
      lineups: [
        { teamId: 'team-a', setNumber: 1, activePlayerIds: ['p-a1', 'p-a2'], benchPlayerId: 'p-a3' },
        { teamId: 'team-b', setNumber: 1, activePlayerIds: ['p-b1', 'p-b2'], benchPlayerId: 'p-b3' },
        { teamId: 'team-a', setNumber: 2, activePlayerIds: ['p-a1', 'p-a3'], benchPlayerId: 'p-a2' },
        { teamId: 'team-b', setNumber: 2, activePlayerIds: ['p-b2', 'p-b3'], benchPlayerId: 'p-b1' },
      ],
      currentKaosEventId: 'kaos-1',
      activeCardUsageIds: ['usage-1'],
    },
    {
      id: 'match-2',
      courtId: 'court-2',
      groupId: 'g-beta',
      teamAId: 'team-c',
      teamBId: 'team-d',
      status: 'live',
      score: { currentSet: 1, points: { A: '15', B: '40' }, games: { A: 4, B: 4 }, sets: { A: 0, B: 0 } },
      lineups: [
        { teamId: 'team-c', setNumber: 1, activePlayerIds: ['p-c1', 'p-c2'], benchPlayerId: 'p-c3' },
        { teamId: 'team-d', setNumber: 1, activePlayerIds: ['p-d1', 'p-d2'], benchPlayerId: 'p-d3' },
      ],
      activeCardUsageIds: [],
    },
  ],
  cards: [
    {
      id: 'card-x3',
      name: 'X3 Point',
      slug: 'x3-point',
      description: 'Il prossimo punto vale triplo per la challenge globale.',
      category: 'bonus',
      target: 'own_team',
      activationTiming: 'before_point',
      durationType: 'point',
      durationValue: 1,
      effectType: 'triple_point',
      isGlobal: false,
      enabled: true,
    },
    {
      id: 'card-freeze',
      name: 'Freeze Serve',
      slug: 'freeze-serve',
      description: 'Gli avversari giocano il prossimo game solo con seconda di servizio.',
      category: 'malus',
      target: 'opponent',
      activationTiming: 'between_games',
      durationType: 'game',
      durationValue: 1,
      effectType: 'second_serve_only',
      isGlobal: false,
      enabled: true,
    },
    {
      id: 'card-kaos',
      name: 'Instant Kaos',
      slug: 'instant-kaos',
      description: 'Attiva overlay main display e notifica tutti i campi.',
      category: 'kaos',
      target: 'global',
      activationTiming: 'anytime',
      durationType: 'match',
      durationValue: 1,
      effectType: 'global_overlay',
      isGlobal: true,
      enabled: true,
    },
  ],
  teamCards: [
    { id: 'tc-1', teamId: 'team-a', cardId: 'card-x3', state: 'available' },
    { id: 'tc-2', teamId: 'team-a', cardId: 'card-freeze', state: 'active' },
    { id: 'tc-3', teamId: 'team-b', cardId: 'card-kaos', state: 'pending' },
    { id: 'tc-4', teamId: 'team-c', cardId: 'card-x3', state: 'available' },
  ],
  diceRules: [
    { id: 'dice-1', value: 1, title: '1 vs 1', description: 'Un solo giocatore per squadra fino al prossimo game.', effectType: 'one_vs_one', durationGames: 1, enabled: true },
    { id: 'dice-2', value: 2, title: 'Punto Doppio', description: 'Ogni punto vale doppio per due game.', effectType: 'double_point', durationGames: 2, enabled: true },
    { id: 'dice-3', value: 3, title: 'Solo Seconda', description: 'Niente prima di servizio fino a fine game.', effectType: 'second_serve_only', durationGames: 1, enabled: true },
    { id: 'dice-4', value: 4, title: 'Golden Point', description: 'Sul 40-40 decide il punto secco.', effectType: 'golden_point', durationGames: 2, enabled: true },
    { id: 'dice-5', value: 5, title: 'No Smash', description: 'Smash vietato per due game.', effectType: 'no_smash', durationGames: 2, enabled: true },
    { id: 'dice-6', value: 6, title: 'Super Kaos', description: 'Arbitro pesca una regola speciale configurata.', effectType: 'super_kaos', enabled: true },
  ],
  kaosEvents: [
    { id: 'kaos-1', matchId: 'match-1', diceRuleId: 'dice-4', diceValue: 4, startedAt: '2026-08-29T19:42:00.000Z' },
  ],
  matchEvents: [
    { id: 'ev-1', matchId: 'match-1', type: 'MATCH_STARTED', payload: { court: 'Campo 1' }, actorUserId: 'ref-1', createdAt: '2026-08-29T19:00:00.000Z' },
    { id: 'ev-2', matchId: 'match-1', type: 'DICE_ROLLED', payload: { value: 4, rule: 'Golden Point' }, actorUserId: 'ref-1', createdAt: '2026-08-29T19:42:00.000Z' },
    { id: 'ev-3', matchId: 'match-1', type: 'CARD_PLAYED', payload: { teamId: 'team-b', cardId: 'card-kaos' }, actorUserId: 'p-b2', createdAt: '2026-08-29T19:44:00.000Z' },
    { id: 'ev-4', matchId: 'match-2', type: 'POINT_SCORED', payload: { side: 'B' }, actorUserId: 'ref-2', createdAt: '2026-08-29T19:45:00.000Z' },
  ],
  globalEvents: [
    {
      id: 'global-x3',
      type: 'prize',
      title: 'PRIMO X3 VINCE UN PREMIO',
      description: 'Il primo giocatore che chiude un punto X3 prende il bonus sponsor.',
      status: 'active',
      prize: 'Cena team + wild card finale',
      startedAt: '2026-08-29T19:30:00.000Z',
    },
  ],
  standings: [
    { teamId: 'team-a', played: 2, won: 2, lost: 0, points: 6 },
    { teamId: 'team-b', played: 2, won: 1, lost: 1, points: 3 },
    { teamId: 'team-c', played: 1, won: 1, lost: 0, points: 3 },
    { teamId: 'team-d', played: 1, won: 0, lost: 1, points: 0 },
  ],
}
