import {readFileSync} from 'node:fs'
import ts from 'typescript'
import {describe,expect,it,vi} from 'vitest'

const source=readFileSync(new URL('./index.ts',import.meta.url),'utf8')
type Dependencies={getTournamentStatus:(id:string)=>Promise<string>;listProfiles:(id:string)=>Promise<Array<{id:string;role:string}>>;clearProfileDependencies:(userId:string,tournamentId:string)=>Promise<void>;deleteAuthUser:(id:string)=>Promise<{error:null|{status?:number;message?:string}}> ;deleteProfile:(userId:string,tournamentId:string)=>Promise<void>}
function loadCleanup(){const executable=source.replace(/^import .*\r?\n/,'const createClient=()=>({})\n').replace('Deno.serve(async (request) => {','globalThis.__edgeHandler = (async (request) => {');const js=ts.transpileModule(executable,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{} as Record<string,unknown>};new Function('exports','module','Response','crypto','console','Deno',js)(module.exports,module,Response,crypto,console,{env:{get:()=>undefined}});return module.exports.cleanupTournamentAuth as (tournamentId:string,callerId:string,deps:Dependencies)=>Promise<{deleted:number;alreadyMissing:number;failed:number;failures?:Array<{phase:string;code:string}>}>}
function dependencies():Dependencies{return{getTournamentStatus:vi.fn(async()=> 'draft'),listProfiles:vi.fn(async()=>[{id:'team-user',role:'team'}]),clearProfileDependencies:vi.fn(async()=>{}),deleteAuthUser:vi.fn(async()=>({error:null})),deleteProfile:vi.fn(async()=>{})}}

describe('provision-tournament-user single-file contract',()=>{
  it('has exactly one external import and no relative imports',()=>{const imports=[...source.matchAll(/^import\s.+from\s+['"]([^'"]+)['"]/gm)].map(match=>match[1]);expect(imports).toEqual(['https://esm.sh/@supabase/supabase-js@2']);expect(source).not.toMatch(/from\s+['"]\.{1,2}\//)})
  it('preserves provision, reset, bulk and cleanup request actions',()=>{expect(source).toContain("'provision' | 'reset_password' | 'cleanup_tournament_auth' | 'delete_tournament'");expect(source).toContain('if (input.bulkTeams)');expect(source).toContain("input.action === 'cleanup_tournament_auth'")})
  it('resets only a non-Admin account scoped to the selected tournament',()=>{expect(source).toContain("input.action === 'reset_password'");expect(source).toContain(".eq('id', input.userId).eq('tournament_id', input.tournamentId).neq('role', 'admin')");expect(source).toContain('auth.admin.updateUserById')})
  it('authenticates the bearer token and verifies tournament Admin membership',()=>{expect(source).toContain('adminClient.auth.getUser(token)');expect(source).toContain("from('tournament_admins')");expect(source).toContain("profile.role!=='admin'")})
  it('requires explicit confirmation for active tournaments and stops on partial Auth cleanup',()=>{expect(source).toContain('active tournament confirmation required');expect(source).toContain('if(cleanup.failed>0)return');expect(source).toContain('tournamentDeleted:false')})
  it('deletes only tournament-scoped dice images recursively',()=>{expect(source).toContain("storage.from('dice-effect-images')");expect(source).toContain('await collect(path)');expect(source).not.toContain("storage.from('card-images')")})
  it('preserves Admin Auth accounts and verifies the final tournament deletion',()=>{expect(source).toContain(".neq('role','admin')");expect(source).toContain(".eq('role','admin')");expect(source).toContain("throw new Error('tournament was not deleted')")})
  it('keeps server secrets in Deno environment variables',()=>{expect(source).toContain("Deno.env.get('SUPABASE_SECRET_KEYS')");expect(source).toContain("Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')");expect(source).not.toMatch(/service_role\s*[:=]\s*['"][A-Za-z0-9._-]+/i)})
})

describe('idempotent tournament Auth cleanup',()=>{
  const cleanup=loadCleanup()
  it('reports an Auth failure with its phase and leaves the profile untouched',async()=>{const deps=dependencies();vi.mocked(deps.deleteAuthUser).mockResolvedValue({error:{status:500,message:'Auth unavailable'}});await expect(cleanup('target','admin',deps)).resolves.toMatchObject({failed:1,failures:[{phase:'auth_delete',code:'500'}]});expect(deps.deleteProfile).not.toHaveBeenCalled()})
  it('reports dependency and profile failures separately',async()=>{const first=dependencies();vi.mocked(first.clearProfileDependencies).mockRejectedValue(Object.assign(new Error('FK'),{code:'23503'}));await expect(cleanup('target','admin',first)).resolves.toMatchObject({failed:1,failures:[{phase:'profile_dependencies',code:'23503'}]});const second=dependencies();vi.mocked(second.deleteProfile).mockRejectedValue(Object.assign(new Error('profile blocked'),{code:'23503'}));await expect(cleanup('target','admin',second)).resolves.toMatchObject({failed:1,failures:[{phase:'profile_delete',code:'23503'}]})})
  it('treats an already absent Auth user as recoverable and removes the residual profile',async()=>{const deps=dependencies();vi.mocked(deps.deleteAuthUser).mockResolvedValue({error:{status:404,message:'User not found'}});await expect(cleanup('target','admin',deps)).resolves.toMatchObject({alreadyMissing:1,failed:0});expect(deps.deleteProfile).toHaveBeenCalledWith('team-user','target')})
  it('is safe to retry after a transient Auth error',async()=>{const deps=dependencies();vi.mocked(deps.deleteAuthUser).mockResolvedValueOnce({error:{status:503,message:'temporary'}}).mockResolvedValueOnce({error:null});await expect(cleanup('target','admin',deps)).resolves.toMatchObject({failed:1});await expect(cleanup('target','admin',deps)).resolves.toMatchObject({deleted:1,failed:0})})
  it('passes the target tournament to every mutation and skips Admin accounts',async()=>{const deps=dependencies();vi.mocked(deps.listProfiles).mockResolvedValue([{id:'other-admin',role:'admin'},{id:'team-user',role:'team'}]);await cleanup('target','admin',deps);expect(deps.clearProfileDependencies).toHaveBeenCalledTimes(1);expect(deps.clearProfileDependencies).toHaveBeenCalledWith('team-user','target');expect(deps.deleteProfile).toHaveBeenCalledWith('team-user','target')})
})
