import { useMemo, useState } from 'react'
import { Alert, Box, Button, Card, CardActions, CardContent, CardMedia, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Stack, Switch, TextField, Typography } from '@mui/material'
import Add from '@mui/icons-material/Add'
import Image from '@mui/icons-material/Image'
import { diceFaces } from '../../../domain/live/diceShow'
import { dataProvider } from '../../../repositories'
import { useDiceEffectRepository, type DiceEffectDraft } from '../../../repositories/diceEffectRepository'
import type { DiceRule } from '../../../shared/types/domain'
import type { WorkspaceEntry } from '../workspace/workspaceStore'

const emptyDraft:DiceEffectDraft={title:'',description:'',longDescription:'',imageUrl:null,enabled:true}
export function DiceLibraryPanel({entry}:{entry:WorkspaceEntry}){
  const repository=useDiceEffectRepository(entry.domain.id);const[editing,setEditing]=useState<DiceRule|null>(null);const[draft,setDraft]=useState(emptyDraft);const[open,setOpen]=useState(false);const[file,setFile]=useState<File|null>(null);const[error,setError]=useState('')
  const preview=useMemo(()=>file?URL.createObjectURL(file):null,[file]);const locked=entry.config.started||['live','completed'].includes(entry.config.status)||entry.domain.status==='archived';const remote=dataProvider==='supabase'
  const begin=(rule?:DiceRule)=>{setEditing(rule??null);setDraft(rule?{title:rule.title,description:rule.description,longDescription:rule.longDescription??rule.description,imageUrl:rule.imageUrl??null,enabled:rule.enabled}:emptyDraft);setFile(null);setError('');setOpen(true)}
  const save=async()=>{if(!draft.title.trim()||!draft.description.trim()||!draft.longDescription.trim()){setError('Compila nome e descrizioni.');return}try{let rule=editing??await repository.create(draft);let next={...draft};if(file){const url=await repository.upload(rule.id,file);next={...next,imageUrl:url}}rule=await repository.update(rule.id,next);if(editing?.imageUrl&&editing.imageUrl!==next.imageUrl)await repository.remove(editing.id,editing.imageUrl);setEditing(rule);setOpen(false)}catch(cause){setError(cause instanceof Error?cause.message:'Impossibile salvare l’effetto dado.')}}
  return <Stack spacing={3}><Stack direction={{xs:'column',sm:'row'}} sx={{justifyContent:'space-between',gap:2}}><Box><Typography variant="h2">Libreria Dado</Typography><Typography color="text.secondary">La libreria può contenere più di sei effetti. In Regia ne verranno scelti esattamente sei per ogni turno.</Typography></Box><Button startIcon={<Add/>} variant="contained" disabled={!remote||locked} onClick={()=>begin()}>NUOVO EFFETTO</Button></Stack>{locked&&<Alert severity="info">La libreria del dado è bloccata durante il torneo.</Alert>}{error&&<Alert severity="error">{error}</Alert>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr',xl:'repeat(3,1fr)'},gap:3}}>{entry.domain.diceRules.map(rule=>{const fallback=diceFaces.find(face=>face.productCode===rule.productCode)||diceFaces.find(face=>face.value===rule.value);return <Card key={rule.id} sx={{display:'flex',flexDirection:'column'}}>{rule.imageUrl||fallback?.artwork?<CardMedia component="img" height="180" image={rule.imageUrl||fallback?.artwork} alt={`Effetto dado ${rule.title}`} sx={{objectFit:'cover'}}/>:<Box sx={{height:180,display:'grid',placeItems:'center'}}><Image sx={{fontSize:56}}/></Box>}<CardContent sx={{flex:1}}><Stack direction="row" sx={{justifyContent:'space-between',gap:1}}><Typography variant="h3">{rule.title}</Typography><Chip size="small" color={rule.enabled?'success':'default'} label={rule.enabled?'ATTIVO':'DISATTIVO'}/></Stack><Typography sx={{mt:1,fontWeight:750}}>{rule.description}</Typography><Typography variant="body2" color="text.secondary" sx={{mt:2}}>{rule.longDescription??rule.description}</Typography></CardContent><CardActions><Button disabled={!remote||locked} onClick={()=>begin(rule)}>MODIFICA</Button><Button disabled={!remote||locked||repository.isPending} onClick={()=>void repository.update(rule.id,{title:rule.title,description:rule.description,longDescription:rule.longDescription??rule.description,imageUrl:rule.imageUrl??null,enabled:!rule.enabled})}>{rule.enabled?'DISATTIVA':'ATTIVA'}</Button></CardActions></Card>})}</Box>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing?'Modifica effetto':'Nuovo effetto dado'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{preview||draft.imageUrl?<CardMedia component="img" height="180" image={preview||draft.imageUrl||''} alt="Anteprima effetto dado" sx={{objectFit:'cover'}}/>:<Box sx={{height:150,display:'grid',placeItems:'center'}}><Image sx={{fontSize:54}}/></Box>}<Stack direction="row" spacing={1}><Button component="label" variant="outlined">{preview||draft.imageUrl?'SOSTITUISCI IMMAGINE':'CARICA IMMAGINE'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]??null)}/></Button>{(preview||draft.imageUrl)&&<Button color="error" onClick={()=>{setFile(null);setDraft(current=>({...current,imageUrl:null}))}}>RIMUOVI IMMAGINE</Button>}</Stack><TextField label="Nome" value={draft.title} onChange={event=>setDraft(current=>({...current,title:event.target.value}))}/><TextField label="Descrizione breve" multiline minRows={2} value={draft.description} onChange={event=>setDraft(current=>({...current,description:event.target.value}))}/><TextField label="Descrizione completa" multiline minRows={4} value={draft.longDescription} onChange={event=>setDraft(current=>({...current,longDescription:event.target.value}))}/><FormControlLabel label="Attivo" control={<Switch checked={draft.enabled} onChange={(_,enabled)=>setDraft(current=>({...current,enabled}))}/>} />{error&&<Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>ANNULLA</Button><Button variant="contained" disabled={repository.isPending} onClick={()=>void save()}>SALVA</Button></DialogActions></Dialog></Stack>
}
